name: haskell-in-depth
version: 0.1
synopsis: Notes and exercises for the book "Haskell in Depth"
description: Sample Code
category: Sample Code
license: MIT
author: Gabriele Lana
maintainer: Gabriele Lana <gabriele.lana@gmail.com>
github: gabrielelana/hashell-in-depth
extra-source-files:
  - README.md
  - stack.yaml
  - package.yaml
  - hie.yaml
  - chapter-01.org

dependencies: base >=4.12 && <4.15

ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wno-unused-top-binds
  - -Wno-orphans

executables:
  text-search:
    source-dirs: chapter-01/text-search
    main: text-search.hs
    other-modules: []
    dependencies:
      - protolude >= 0.3
