name: rpn
version: 0.1.0.0
github: "gabrielelana/rpn"
license: BSD3
author: "Gabriele Lana"
maintainer: "gabriele.lana@gmail.com"
copyright: "Copyright (c) 2021 Gabriele Lana &lt;gabriele.lana@gmail.com&gt;"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/gabrielelana/rpn#readme>

dependencies:
  - base >= 4.7 && < 5
  - parsec
  - hspec

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  rpn-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - rpn

tests:
  rpn-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - rpn
